[package]
name = "openai"
version = "0.0.1"
edition = "2021"

[dependencies]
async-openai = "0.10.3"
clap = { version = "4.3.2", features = ["derive"] }
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["macros", "rt", "rt-multi-thread"] }
